services:
  web:
    build:
      context: .
      args:
        - PORT=8080
  
  nginx:
    build:
      context: .
      dockerfile: nginx.dev.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./static:/static
    depends_on:
      - web