services:
  web:
    build:
      context: .
      args:
        - PORT=8080
    volumes:
      - ./logs:/opt/mnt/logs
  
  nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf_dev:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web